# Generated by Django 4.0.3 on 2022-03-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0003_alter_shortener_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shortener',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
