# Generated by Django 4.0.3 on 2022-04-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0004_shortener_active_shortener_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
