# Generated by Django 4.0.3 on 2022-04-23 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0005_shortener_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=152)),
                ('user_agent', models.TextField()),
                ('country', models.CharField(max_length=150)),
                ('lat', models.CharField(max_length=150)),
                ('long', models.CharField(max_length=150)),
                ('visited', models.DateTimeField(auto_now_add=True)),
                ('shortener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selfurl.shortener')),
            ],
            options={
                'ordering': ['-visited'],
            },
        ),
    ]
