# Generated by Django 4.0.3 on 2022-04-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0006_visitorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.URLField(max_length=2000),
        ),
    ]
