# Generated by Django 4.0.3 on 2022-06-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0007_alter_shortener_long_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='country',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortener',
            name='ip',
            field=models.CharField(default='', max_length=152),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortener',
            name='lat',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortener',
            name='long',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortener',
            name='user_agent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
