# Generated by Django 4.0.3 on 2022-07-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfurl', '0008_shortener_country_shortener_ip_shortener_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMalicious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporturl', to='selfurl.shortener')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
