# Generated by Django 4.0.3 on 2022-07-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfurl', '0009_reportmalicious'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='remark',
        ),
    ]
