# Generated by Django 4.0.3 on 2022-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_remove_exsite_site_meta_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(choices=[('index', 'Index'), ('redirect_url', 'Redirect_url'), ('report_malicious', 'Report_malicious'), ('click_counter', 'Click_counter'), ('contact', 'Contact'), ('webmanifest', 'Webmanifest'), ('terms_and_conditions', 'Terms_and_conditions'), ('privacy_policy', 'Privacy_policy')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('footer', 'Footer'), ('header', 'Header')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='acordion',
            name='path',
            field=models.CharField(choices=[('index', 'Index'), ('redirect_url', 'Redirect_url'), ('report_malicious', 'Report_malicious'), ('click_counter', 'Click_counter'), ('contact', 'Contact'), ('webmanifest', 'Webmanifest'), ('terms_and_conditions', 'Terms_and_conditions'), ('privacy_policy', 'Privacy_policy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='metatext',
            name='path',
            field=models.CharField(choices=[('index', 'Index'), ('redirect_url', 'Redirect_url'), ('report_malicious', 'Report_malicious'), ('click_counter', 'Click_counter'), ('contact', 'Contact'), ('webmanifest', 'Webmanifest'), ('terms_and_conditions', 'Terms_and_conditions'), ('privacy_policy', 'Privacy_policy')], max_length=50),
        ),
    ]
