# Generated by Django 4.0.3 on 2022-04-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_alter_acordion_path_alter_menus_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='arg_require',
            field=models.BooleanField(default=False),
        ),
    ]
