# Generated by Django 4.0.3 on 2022-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_menus_arg_require'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='arg_require',
        ),
        migrations.AddField(
            model_name='menus',
            name='args',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
    ]
