# Generated by Django 4.0.3 on 2022-04-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_alter_acordion_path_alter_menus_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='args',
        ),
    ]
