# Generated by Django 4.0.3 on 2022-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_remove_menus_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='exsite',
            name='reported_url_limit',
            field=models.IntegerField(default=3),
        ),
    ]
