# Generated by Django 4.0.3 on 2022-04-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0016_alter_acordion_path_alter_menus_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatext',
            name='title',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metatext',
            name='description',
            field=models.TextField(max_length=160),
        ),
    ]
