# Generated by Django 4.0.3 on 2022-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0017_metatext_title_alter_metatext_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordion',
            name='fa_icon_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
