# Generated by Django 4.0.3 on 2022-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0023_alter_acordion_path_alter_menus_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exsite',
            name='site_meta_tag',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
