# Generated by Django 4.0.3 on 2022-04-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Enter Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter Email')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('message', models.TextField(max_length=1000, verbose_name='Messages')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='sites.site', verbose_name='ContactsTo')),
            ],
        ),
    ]
